// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

type Env = {
  DATABASE_URL: string;
};

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Read DATABASE_URL from the environment (and error nicely if it's missing)
    url: env<Env>('DATABASE_URL'),
  },
});
